name: tasky_app
description: "A new modern task manager"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.5.1


dependencies:
  flutter:
    sdk: flutter
  lottie: ^3.1.2
  flutter_svg: ^2.0.10+1
  intl: ^0.19.0
  provider: ^6.1.2

  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^4.0.0



flutter:

  uses-material-design: true

  assets:
    - assets/animations/splash_animation.json
    - assets/icons/home.svg
    - assets/icons/notification.svg
    - assets/icons/calendar.svg
    - assets/images/todo.svg
    - assets/images/bg.svg
    - assets/icons/calendar_icon.svg
    - assets/icons/arrow-right.svg
    - assets/icons/short_left.svg
    - assets/icons/search.svg
    - assets/images/missing.svg
    - assets/icons/check.svg
    - assets/icons/edit.svg

  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Regular.ttf
        - asset: assets/fonts/Poppins-SemiBold.ttf
          style: italic